---
- hosts: localhost
  connection: local
  vars:
    temporary_directory: /tmp/ansible_temporary
  pre_tasks:
    - name: テンポラリディレクトリ作成
      ansible.builtin.file:
        path: "{{ temporary_directory }}"
        state: directory
        mode: 0755

  roles:
    - role: fonts
    - role: google-chrome
    - role: docker
    - role: jetbrains-toolbox

  post_tasks:
    - name: テンポラリディレクトリを削除
      ansible.builtin.file:
        path: "{{ temporary_directory }}"
        state: absent
